### ISSUE TITLE
The bot is not responding.

### ISSUE THREAD

**Issue by ghost** [RajKKapadia/Telegram-Bot-Python#1]
Hello, I hope you are very well, I have followed the installation guide as it says in your repository and I also watched your complete video. Everything is going well, I even did the tests in Insomnia and the answer appears on the console. But when I send the command to the boy on telegram I don't get any response from the bot.

![Captura de Pantalla 2023-01-04 a la(s) 18 22 40](https://user-images.githubusercontent.com/26399120/210669348-124791b7-7c31-48e0-8eed-a5075bbc314b.png)
![Captura de Pantalla 2023-01-04 a la(s) 18 22 46](https://user-images.githubusercontent.com/26399120/210669351-34ad000b-4b82-41ff-bee5-13292ec77157.png)

**Comment by ghost** [comment]
> Hello, I hope you are very well, I have followed the installation guide as it says in your repository and I also watched your complete video. Everything is going well, I even did the tests in Insomnia and the answer appears on the console. But when I send the command to the boy on telegram I don't get any response from the bot.
> 
> ![Captura de Pantalla 2023-01-04 a la(s) 18 22 40](https://user-images.githubusercontent.com/26399120/210669348-124791b7-7c31-48e0-8eed-a5075bbc314b.png) ![Captura de Pantalla 2023-01-04 a la(s) 18 22 46](https://user-images.githubusercontent.com/26399120/210669351-34ad000b-4b82-41ff-bee5-13292ec77157.png)

![Captura de Pantalla 2023-01-04 a la(s) 18 36 07](https://user-images.githubusercontent.com/26399120/210670078-99a7b8b6-f84c-49c5-910a-8839d6bfa22b.png)

**Comment by RajKKapadia** [comment]
It will be good if you list all the steps you performed, but I think you missed the step to set the webhook explained in the README file...

Try that and let me know... I will close this issue for now...

Regards,
Raj Kapadia
